/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ad.ieseljust.practica3;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author jasb
 */
public class GestioW extends javax.swing.JFrame {

    private ConnexioBD conn;

    /**
     * Creates new form Validacio
     */
    public GestioW() {
        try {
            initComponents();

            setLocationRelativeTo(null);

            conn = new ConnexioBD();
            conn.connectMySQL("");
            Connection connexio = conn.getLaConnexio();

            DatabaseMetaData dbmd = connexio.getMetaData();

            /* Mostrar els esquemes disponibles del SGBD */
            ArrayList<String> db = new ArrayList<>();
            ResultSet rsbd = dbmd.getCatalogs();

            while (rsbd.next()) {
                if (!rsbd.getString(1).equals("information_schema") && !rsbd.getString(1).equals("mysql") && !rsbd.getString(1).equals("performance_schema")
                        && !rsbd.getString(1).equals("sys")) {
                    db.add(rsbd.getString(1));
                }
            }

            // Convertir el ArrayList a un array
            String[] opcions = db.toArray(new String[0]);
            int resposta = JOptionPane.showOptionDialog(
                    null,
                    "Selecciona la Base de Dades:",
                    "Connectar a Base de Dades",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    opcions,
                    opcions[0]
            );

            if (resposta != JOptionPane.CLOSED_OPTION) {

                conn.connectMySQL(opcions[resposta]);

                ArrayList<String> taules = new ArrayList<>();
                ResultSet rstb = dbmd.getTables(opcions[resposta], null, null, null);
                while (rstb.next()) {
                    taules.add(rstb.getString(3));
                }

                // Convertir el ArrayList a un array
                String[] opcionsT = taules.toArray(new String[0]);
                int respostaT = JOptionPane.showOptionDialog(
                        null,
                        "Quina taula vols gestionar?",
                        "Gestionar taula de " + opcions[resposta],
                        JOptionPane.DEFAULT_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        opcionsT,
                        opcionsT[0]
                );

                if (respostaT != JOptionPane.CLOSED_OPTION) {
                    setTitle("Taula '" + opcionsT[respostaT] + "'");
                }

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,
                    "ERROR: " + ex.getMessage(),
                    "Instituto APP", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbInsertar = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();
        jbExit = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbImport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jbInsertar.setText("Insertar");
        jbInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInsertData(evt);
            }
        });

        jbCancel.setText("Consultar");
        jbCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQeryData(evt);
            }
        });

        jbExit.setBackground(new java.awt.Color(255, 204, 204));
        jbExit.setText("Eixir");
        jbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExitActionPerformed(evt);
            }
        });

        jbModificar.setText("Modificar");
        jbModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModifyData(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeleteData(evt);
            }
        });

        jbImport.setBackground(new java.awt.Color(204, 255, 204));
        jbImport.setText("Importar datos");
        jbImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbImportarCSV(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbImport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jbImport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbInsertar)
                .addGap(18, 18, 18)
                .addComponent(jbCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jbModificar)
                .addGap(18, 18, 18)
                .addComponent(jbEliminar)
                .addGap(18, 18, 18)
                .addComponent(jbExit)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbQeryData(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQeryData
        // TODO add your handling code here:
        queries();
    }//GEN-LAST:event_jbQeryData

    private void jbInsertData(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInsertData
        // TODO add your handling code here:
        insert();
    }//GEN-LAST:event_jbInsertData

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_formWindowClosing

    private void jbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExitActionPerformed
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_jbExitActionPerformed

    private void jbModifyData(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModifyData
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_jbModifyData

    private void jbDeleteData(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeleteData
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_jbDeleteData

    private void jbImportarCSV(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbImportarCSV
        // TODO add your handling code here:
        importar();
    }//GEN-LAST:event_jbImportarCSV


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbExit;
    private javax.swing.JButton jbImport;
    private javax.swing.JButton jbInsertar;
    private javax.swing.JButton jbModificar;
    // End of variables declaration//GEN-END:variables

    private void exit() {
        conn.disConnect();
        this.setVisible(false);
        System.exit(0);
    }

    private void importar() {
        conn.importar();

    }

    private void delete() {
        conn.eliminar();

    }

    private void insert() {
        conn.insertar();

    }

    private void queries() {

        QueryW queriesW = new QueryW(this.conn);
        queriesW.setVisible(true);
    }

    private void update() {

        ModifyW updW = new ModifyW(this.conn);
        updW.setVisible(true);
    }
}
