DROP DATABASE IF EXISTS 42k;

CREATE DATABASE 42k CHARACTER SET utf8mb4;

USE 42k;

CREATE TABLE Runner (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(50),
  edat INT NOT NULL,
  num_marathons INT NOT NULL,
  pais VARCHAR(25) NOT NULL,
  logro VARCHAR(100)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;